"""
dead_reckoning.py

Implements a simple pedestrian dead-reckoning pipeline based on the spec:
- Loads .npz produced by data_simulation.py (expects arrays: t, gt_pos, gt_heading, acc, gyro, gps_pos, gps_available, step_times, step_indices)
- detect_steps(): peak detection on acceleration magnitude with an adaptive threshold
- estimate_heading(): integrate gyro z + complementary filter using a simulated magnetometer (from gt_heading + noise if available)
- reconstruct_position(): use fixed average step length to update position at each detected step
- main: runs the pipeline, plots ground truth vs DR path, prints mean and max position error

Keep functions simple and importable for later ML/Kalman fusion work.

Author: Generated by an AI assistant using Copilot CLI runtime in VS Code
"""

import os
import numpy as np
import matplotlib.pyplot as plt

try:
    from scipy.signal import find_peaks
    _HAVE_SCIPY = True
except Exception:
    _HAVE_SCIPY = False


def detect_steps(accel, fs=None, window_s=1.0, rel_thresh_scale=0.5, min_distance_s=0.3):
    """
    Detect steps from accelerometer samples (N x 3) using peaks on magnitude.

    Parameters
    - accel: ndarray shape (N,3) with ax,ay,az in m/s^2
    - fs: sampling frequency in Hz (optional). If provided, min_distance_s is used to set minimum peak distance.
    - window_s: window length in seconds for local statistics used to compute adaptive threshold
    - rel_thresh_scale: multiplier for (median + rel_thresh_scale * mad) to set threshold
    - min_distance_s: minimum separation between peaks in seconds

    Returns
    - peak_indices: ndarray of sample indices where steps were detected
    - mag: acceleration magnitude array
    - thresh: final threshold array (same length as mag)
    """
    accel = np.asarray(accel)
    if accel.ndim != 2 or accel.shape[1] != 3:
        raise ValueError("accel must be N x 3")

    mag = np.linalg.norm(accel, axis=1)
    N = mag.size

    # If fs given, compute window size in samples
    if fs is not None:
        win = max(3, int(window_s * fs))
        min_distance = int(min_distance_s * fs)
    else:
        win = max(3, int(window_s * 50))  # assume 50Hz if unknown for windowing
        min_distance = max(1, int(min_distance_s * 50))

    # Compute running median and MAD (robust)
    # Use simple sliding approach: pad and compute median for each window center
    pad = win // 2
    padded = np.pad(mag, pad_width=pad, mode='reflect')
    med = np.array([np.median(padded[i:i+win]) for i in range(N)])

    # MAD
    def mad(x):
        return np.median(np.abs(x - np.median(x)))

    mad_vals = np.array([mad(padded[i:i+win]) for i in range(N)])

    # Adaptive threshold: median + k * MAD
    thresh = med + rel_thresh_scale * mad_vals

    # Minimum prominence: require peaks exceed threshold and have some prominence
    if _HAVE_SCIPY:
        peaks, props = find_peaks(mag, height=thresh, distance=min_distance, prominence=0.1)
    else:
        # Fallback: simple peak finding
        peaks = []
        for i in range(1, N-1):
            if mag[i] > mag[i-1] and mag[i] > mag[i+1] and mag[i] > thresh[i]:
                peaks.append(i)
        # enforce minimum distance
        if len(peaks) > 1:
            filtered = [peaks[0]]
            for p in peaks[1:]:
                if p - filtered[-1] >= min_distance:
                    filtered.append(p)
            peaks = np.array(filtered, dtype=int)
        else:
            peaks = np.array(peaks, dtype=int)

    return np.array(peaks, dtype=int), mag, thresh


def estimate_heading(gyro_z, t=None, alpha=0.98, mag_heading=None):
    """
    Estimate heading by integrating gyro z and applying a complementary filter with a (simulated) magnetometer.

    Parameters
    - gyro_z: ndarray shape (N,) angular velocity around z in rad/s (positive CCW)
    - t: ndarray shape (N,) timestamps in seconds (optional). If None, uniform sampling assumed dt=1.
    - alpha: complementary filter coefficient for gyro (0..1). Higher alpha trusts gyro more.
    - mag_heading: optional ndarray shape (N,) providing magnetometer heading in radians. If provided, used by the complementary filter.

    Returns
    - heading: ndarray shape (N,) estimated heading in radians (unwrapped)
    """
    gyro_z = np.asarray(gyro_z).flatten()
    N = gyro_z.size
    if t is None:
        dt = 1.0
        t = np.arange(N) * dt
    else:
        t = np.asarray(t).flatten()
        dt = np.diff(t, prepend=t[0])

    # Integrate gyro to get a raw heading estimate
    gyro_heading = np.cumsum(gyro_z * dt)

    # If mag_heading not provided, we'll return gyro_heading (but caller may pass gt-based simulated mag)
    if mag_heading is None:
        # return unfiltered but unwrapped
        return np.unwrap(gyro_heading)

    mag_heading = np.asarray(mag_heading).flatten()
    if mag_heading.size != N:
        raise ValueError("mag_heading must be same length as gyro_z/t")

    # Complementary filter: h = alpha*(h_prev + gyro*dt) + (1-alpha)*mag
    h = np.zeros(N)
    h[0] = mag_heading[0]
    for i in range(1, N):
        pred = h[i-1] + gyro_z[i] * dt[i]
        # unwrap pred and mag to avoid jumps
        # compute difference between pred and mag in [-pi,pi]
        diff = (mag_heading[i] - pred + np.pi) % (2*np.pi) - np.pi
        h[i] = alpha * pred + (1 - alpha) * (pred + diff)

    return np.unwrap(h)


def reconstruct_position(initial_pos, step_indices, heading, step_length=0.7):
    """
    Reconstruct 2D positions from steps.

    Parameters
    - initial_pos: (2,) array-like starting [x,y]
    - step_indices: array of sample indices where steps occurred
    - heading: ndarray of headings (radians) aligned with samples
    - step_length: fixed step length in meters

    Returns
    - dr_positions: ndarray shape (M,2) positions after each step (including initial position as first row)
    - dr_times_idx: ndarray shape (M,) corresponding sample indices (first entry corresponds to initial_pos at -1 or step_indices[0] depending)
    """
    pos = np.array(initial_pos, dtype=float)
    positions = [pos.copy()]
    indices = [None]  # initial position index unknown

    for idx in step_indices:
        # use heading at step time
        theta = heading[idx]
        dx = step_length * np.cos(theta)
        dy = step_length * np.sin(theta)
        pos = pos + np.array([dx, dy])
        positions.append(pos.copy())
        indices.append(int(idx))

    return np.vstack(positions), np.array(indices)


def haversine_dist(a, b):
    """
    Simple Euclidean distance for planar coords. If inputs are lat/lon in degrees, this is NOT correct.
    Here assume gt_pos and reconstructed positions are in meters in same frame.
    """
    return np.linalg.norm(a - b, axis=1)


def main(npz_path, step_length=0.7, plot=True):
    """
    Runs the full pipeline on the provided .npz file and (optionally) plots the results.
    """
    data = np.load(npz_path)
    # Required fields from the spec
    t = data['t']
    gt_pos = data['gt_pos']  # shape (N,2)
    if 'gt_heading' in data:
        gt_heading = data['gt_heading']
    else:
        gt_heading = None

    acc = data['acc']  # shape (N,3)
    gyro = data['gyro']  # shape (N,3)

    # Detect steps
    # Try to infer sampling frequency from t
    if t.size >= 2:
        dt = np.median(np.diff(t))
        fs = 1.0 / dt if dt > 0 else None
    else:
        fs = None

    step_indices, mag, thresh = detect_steps(acc, fs=fs)
    print(f"Detected {len(step_indices)} steps")

    # Estimate heading
    gyro_z = gyro[:, 2]
    mag_heading = None
    if gt_heading is not None:
        # Simulate magnetometer heading as ground truth + gaussian noise (small)
        # Assume gt_heading is in radians; if it's in degrees, user can convert upstream
        noise_std = np.deg2rad(3.0)
        rng = np.random.default_rng(42)
        mag_heading = gt_heading + rng.normal(0.0, noise_std, size=gt_heading.shape)

    heading = estimate_heading(gyro_z, t=t, alpha=0.98, mag_heading=mag_heading)

    # Reconstruct position starting from ground-truth initial position to make errors interpretable
    initial_pos = gt_pos[0]
    dr_positions, dr_indices = reconstruct_position(initial_pos, step_indices, heading, step_length=step_length)

    # Prepare ground-truth positions at step times for error computation
    # gt_at_steps: align to the same length as dr_positions by taking gt_pos at each step index; first position is initial
    gt_at_steps = [initial_pos]
    for idx in step_indices:
        gt_at_steps.append(gt_pos[int(idx)])
    gt_at_steps = np.vstack(gt_at_steps)

    # Compute errors per step
    dists = haversine_dist(dr_positions, gt_at_steps)
    mean_err = np.mean(dists)
    max_err = np.max(dists)

    print(f"Dead Reckoning (fixed step length={step_length} m): mean error = {mean_err:.2f} m, max error = {max_err:.2f} m")

    if plot:
        plt.figure(figsize=(8, 6))
        # Ground truth continuous path
        plt.plot(gt_pos[:, 0], gt_pos[:, 1], label='Ground Truth', c='tab:blue')
        # DR reconstructed path (connect step positions)
        plt.plot(dr_positions[:, 0], dr_positions[:, 1], '-o', label='Dead Reckoning (steps)', c='tab:orange')
        # Mark detected step times on the GT path
        plt.scatter(gt_pos[step_indices, 0], gt_pos[step_indices, 1], marker='x', c='red', label='Step times (GT)')

        plt.axis('equal')
        plt.xlabel('X (m)')
        plt.ylabel('Y (m)')
        plt.title('Ground Truth vs Dead Reckoning')
        plt.legend()
        plt.grid(True)
        plt.show()

    return {
        't': t,
        'gt_pos': gt_pos,
        'step_indices': step_indices,
        'mag': mag,
        'thresh': thresh,
        'heading': heading,
        'dr_positions': dr_positions,
        'dr_indices': dr_indices,
        'dists_per_step': dists,
        'mean_error': mean_err,
        'max_error': max_err,
    }


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Run simple dead reckoning from simulated data .npz')
    parser.add_argument('npz', help='Path to the .npz file produced by data_simulation.py')
    parser.add_argument('--step-length', type=float, default=0.7, help='Fixed step length in meters (default: 0.7)')
    args = parser.parse_args()

    result = main(args.npz, step_length=args.step_length, plot=True)
