"""
main.py

Single entry point that ties together data simulation (if desired), dead reckoning, ML step-length model, and Kalman fusion.

Produces a polished matplotlib figure and a short summary table of errors.

Author: Generated by an AI assistant using Copilot CLI runtime in VS Code
"""

import os
import sys
import numpy as np
import matplotlib.pyplot as plt

import dead_reckoning
import ml_step_length
import fusion


def load_or_run_sim(npz_path, run_sim_cmd=None):
    """
    If npz_path exists, return it. Otherwise, if run_sim_cmd provided try to run it to generate the file.
    Provides a helpful error message for the common case where the user has not yet run the simulator.
    """
    if os.path.exists(npz_path):
        return npz_path
    if run_sim_cmd is None:
        # Give a friendly instruction when the common simulated_run.npz is missing
        if os.path.basename(npz_path) == 'simulated_run.npz':
            raise FileNotFoundError("simulated_run.npz not found. Run:\n    python data_simulation.py\nfirst, then run:\n    python main.py")
        raise FileNotFoundError(f"{npz_path} not found and no simulation command provided")
    # Attempt to execute the simulation command to generate the npz
    print('Running data simulation to generate', npz_path)
    rc = os.system(run_sim_cmd)
    if rc != 0:
        raise RuntimeError('data simulation command failed')
    if not os.path.exists(npz_path):
        raise FileNotFoundError('Simulation did not produce expected .npz file')
    return npz_path


def plot_final(gt_pos, naive, fused, dr_fixed_steps, gps_loss_mask, out_png='final_demo_result.png'):
    plt.figure(figsize=(10, 8))
    ax = plt.gca()

    # Plot ground truth
    ax.plot(gt_pos[:, 0], gt_pos[:, 1], c='k', linestyle='-', label='Ground Truth')

    # Plot naive GPS-freeze baseline
    ax.plot(naive[:, 0], naive[:, 1], c='r', linestyle='--', label='Naive GPS-freeze')

    # Plot fused path
    ax.plot(fused[:, 0], fused[:, 1], c='g', linestyle='-', label='Kalman + ML fused')

    # Plot DR-fixed step positions as markers (step-based)
    ax.plot(dr_fixed_steps[:, 0], dr_fixed_steps[:, 1], 'o', color='tab:orange', label='DR (fixed steps)')

    # Shade GPS-loss region along time axis by projecting indices to path extents
    if gps_loss_mask is not None:
        # Simple visualization: find contiguous GPS-loss ranges and draw translucent convex hulls along path
        loss_idxs = np.where(~gps_loss_mask)[0]
        if loss_idxs.size > 0:
            # group contiguous ranges
            ranges = []
            start = loss_idxs[0]
            prev = loss_idxs[0]
            for i in loss_idxs[1:]:
                if i == prev + 1:
                    prev = i
                else:
                    ranges.append((start, prev))
                    start = i
                    prev = i
            ranges.append((start, prev))

            for s, e in ranges:
                # get polygon from naive path between s..e
                seg = np.vstack([naive[s:e+1], fused[s:e+1]])
                ax.fill_between(naive[s:e+1,0], naive[s:e+1,1]-0.1, naive[s:e+1,1]+0.1, color='gray', alpha=0.15)
                # Also mark start/end
                ax.axvline(naive[s,0], color='gray', alpha=0.15)

    ax.set_aspect('equal', adjustable='box')
    ax.set_xlabel('X (m)')
    ax.set_ylabel('Y (m)')
    ax.set_title('Demo: Ground truth vs Naive GPS-freeze vs Kalman+ML fusion')
    ax.legend()
    ax.grid(True)
    plt.tight_layout()
    plt.savefig(out_png, dpi=200)
    print('Saved final figure to', out_png)
    plt.show()


def print_summary_table(errors):
    # errors is dict with keys 'naive', 'dr_fixed', 'dr_var', 'fused' -> (mean,max)
    names = [('Naive GPS-freeze', 'naive'), ('DR (fixed steps)', 'dr_fixed'), ('DR (ML variable)', 'dr_var'), ('Kalman + ML fused', 'fused')]
    print('\nSummary errors (meters):')
    print('{:25s} {:>12s} {:>12s}'.format('Method', 'Mean (m)', 'Max (m)'))
    for display, key in names:
        mean, mx = errors.get(key, (float('nan'), float('nan')))
        print('{:25s} {:12.3f} {:12.3f}'.format(display, mean, mx))


def main(npz_path='data/simulated_run.npz', model_path='step_length_model.joblib', run_sim_cmd=None, out_png='final_demo_result.png'):
    npz_path = load_or_run_sim(npz_path, run_sim_cmd)

    # 1) Dead reckoning (DR-only). Use the dead_reckoning.main to get DR outputs (this will also plot if it is set to)
    dr_result = dead_reckoning.main(npz_path, step_length=0.7, plot=False)

    # 2) Train or load ML model
    if not os.path.exists(model_path):
        print('Training step-length model...')
        ml_step_length.train_and_save_model(npz_path, model_path)
    model_obj = ml_step_length.load_model(model_path)
    model = model_obj if not isinstance(model_obj, tuple) else model_obj[0]

    # 3) Fusion run
    fusion_result = fusion.run_fusion(npz_path, model_path=model_path)

    # 4) Prepare data for plot and summary
    gt_pos = fusion_result['gt_pos']
    naive_pos = fusion_result['naive_positions']
    fused_pos = fusion_result['fused_positions']
    dr_fixed_steps = fusion_result['dr_fixed_positions']
    gps_mask = np.load(npz_path).get('gps_available')

    # 5) Plot final figure and save
    plot_final(gt_pos, naive_pos, fused_pos, dr_fixed_steps, gps_mask, out_png=out_png)

    # 6) Print summary table
    print_summary_table(fusion_result['errors'])

    return fusion_result


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Run end-to-end demo: DR, ML step length, Kalman fusion, final plot')
    parser.add_argument('--npz', default='data/simulated_run.npz', help='Path to data .npz (produced by data_simulation.py)')
    parser.add_argument('--model', default='step_length_model.joblib', help='Path to ML model file')
    parser.add_argument('--run-sim-cmd', default=None, help='Command to run data_simulation.py if .npz not present (e.g. "python data_simulation.py")')
    parser.add_argument('--out', default='final_demo_result.png', help='Output PNG filename')
    args = parser.parse_args()

    main(npz_path=args.npz, model_path=args.model, run_sim_cmd=args.run_sim_cmd, out_png=args.out)
