"""
ml_step_length.py

Train and use a RandomForestRegressor to predict step length from accelerometer-derived features.

API (exported):
- extract_features_for_steps(acc, t, step_indices, window_s=0.5)
- compute_true_step_lengths(gt_pos, gt_step_indices)
- train_and_save_model(npz_path, model_path='step_length_model.joblib')
- load_model(path)
- predict_step_length(features, model)
- reconstruct_path_variable(initial_pos, step_indices, headings, step_lengths)

Notes:
- Reuses detect_steps() from dead_reckoning.py for optional detection checks, but training features/labels are computed from ground-truth step indices when available.
- Requires scikit-learn and joblib. If missing, training will raise an informative error.

Author: Generated by an AI assistant using Copilot CLI runtime in VS Code
"""

import os
import numpy as np

try:
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import r2_score, mean_absolute_error
    import joblib
except Exception as e:
    # Defer failing until train is invoked so other scripts that only import this file don't crash immediately
    RandomForestRegressor = None
    train_test_split = None
    r2_score = None
    mean_absolute_error = None
    joblib = None


def extract_features_for_steps(acc, t, step_indices, fs=None, window_s=0.5):
    """
    Extract features for each step index.

    Features per step:
    - peak acceleration magnitude near the step (max in window)
    - step interval (time since previous step) in seconds
    - acceleration variance in the window around the step

    Returns:
    - features: ndarray (M,3)
    - feature_names: list
    """
    acc = np.asarray(acc)
    t = np.asarray(t)
    N = acc.shape[0]

    if fs is None and t.size >= 2:
        dt = np.median(np.diff(t))
        fs = 1.0 / dt if dt > 0 else 50.0
    if fs is None:
        fs = 50.0

    half_win = int(max(1, round(window_s * fs / 2)))

    mags = np.linalg.norm(acc, axis=1)

    features = []
    for i, idx in enumerate(step_indices):
        idx = int(idx)
        lo = max(0, idx - half_win)
        hi = min(N, idx + half_win + 1)
        window = mags[lo:hi]
        peak = np.max(window) if window.size > 0 else mags[idx]
        var = np.var(window) if window.size > 0 else 0.0
        if i == 0:
            interval = np.nan
        else:
            interval = float(t[idx] - t[int(step_indices[i-1])])
        features.append([peak, interval, var])

    features = np.array(features, dtype=float)
    return features, ['peak_mag', 'dt_since_prev', 'acc_var']


def compute_true_step_lengths(gt_pos, gt_step_indices):
    """
    Compute true step lengths from ground-truth positions at step indices.

    Returns array of length (M-1) corresponding to distances between consecutive steps.
    The first step has no previous step to compare to, so it's dropped.
    """
    gt_pos = np.asarray(gt_pos)
    idx = np.asarray(gt_step_indices, dtype=int)
    if idx.size < 2:
        return np.array([])
    pts = gt_pos[idx]
    diffs = pts[1:] - pts[:-1]
    dists = np.linalg.norm(diffs, axis=1)
    return dists


def train_and_save_model(npz_path, model_path='step_length_model.joblib', test_size=0.2, random_state=42):
    """
    Train a RandomForestRegressor to predict step length and save the model to disk.

    This function expects the .npz to contain at least: t, acc, gt_pos, step_indices (ground-truth step indices).
    """
    if RandomForestRegressor is None:
        raise RuntimeError('scikit-learn and joblib are required to train the model. Install scikit-learn and joblib.')

    data = np.load(npz_path)
    t = data['t']
    acc = data['acc']
    gt_pos = data['gt_pos']

    # Prefer ground-truth step indices for label generation if available
    if 'step_indices' in data:
        gt_step_indices = data['step_indices']
    elif 'step_times' in data and t.size > 0:
        # Map step_times to nearest indices
        step_times = data['step_times']
        gt_step_indices = [int(np.argmin(np.abs(t - st))) for st in step_times]
        gt_step_indices = np.array(gt_step_indices, dtype=int)
    else:
        raise ValueError('data must contain step_indices or step_times for label generation')

    # Extract features at ground-truth step indices
    features, feature_names = extract_features_for_steps(acc, t, gt_step_indices)

    # True step lengths between consecutive GT step events
    true_lengths = compute_true_step_lengths(gt_pos, gt_step_indices)

    # We must drop the first feature row to match label length (labels are distances between consecutive steps)
    if features.shape[0] != true_lengths.shape[0] + 1:
        # If shapes don't align, try to align by trimming longer one
        min_len = min(features.shape[0]-1, true_lengths.shape[0])
        X = features[1:1+min_len]
        y = true_lengths[:min_len]
    else:
        X = features[1:]
        y = true_lengths

    # Handle NaN intervals in first column by simple imputation (median)
    col_dt = X[:, 1]
    median_dt = np.nanmedian(col_dt)
    col_dt[np.isnan(col_dt)] = median_dt
    X[:, 1] = col_dt

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)

    model = RandomForestRegressor(n_estimators=200, random_state=random_state)
    model.fit(X_train, y_train)

    # Evaluate
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)

    # Save model and metadata
    meta = {
        'feature_names': feature_names,
        'median_dt_impute': float(median_dt)
    }
    os.makedirs(os.path.dirname(model_path) or '.', exist_ok=True)
    joblib.dump({'model': model, 'meta': meta}, model_path)

    print(f"Trained RandomForest step-length model saved to {model_path}")
    print(f"Test R^2: {r2:.3f}, MAE: {mae:.3f} m")

    return model_path, r2, mae


def load_model(path='step_length_model.joblib'):
    if joblib is None:
        raise RuntimeError('joblib is required to load the model. Install joblib/scikit-learn.')
    obj = joblib.load(path)
    return obj.get('model', obj), obj.get('meta', {})


def predict_step_length(features, model):
    """
    Predict step lengths from features using the provided model.

    features: (M,3) numpy array
    model: scikit-learn regressor or the joblib object loaded by load_model
    """
    # model may be a dict if loaded raw; handle that
    if isinstance(model, dict) and 'model' in model:
        model = model['model']
    return model.predict(features)


def reconstruct_path_variable(initial_pos, step_indices, headings, step_lengths):
    """
    Reconstruct path when step_lengths is an array (one length per step). Returns positions including initial.
    """
    pos = np.array(initial_pos, dtype=float)
    positions = [pos.copy()]
    for idx, L in zip(step_indices, step_lengths):
        theta = headings[int(idx)]
        dx = L * np.cos(theta)
        dy = L * np.sin(theta)
        pos = pos + np.array([dx, dy])
        positions.append(pos.copy())
    return np.vstack(positions)


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Train step-length ML model from simulated data .npz')
    parser.add_argument('npz', help='Path to the .npz file produced by data_simulation.py')
    parser.add_argument('--out', default='step_length_model.joblib', help='Output model path')
    args = parser.parse_args()

    train_and_save_model(args.npz, args.out)
